#!/usr/bin/env bash
# install-vault-hooks.sh — idempotently install lore's vault pre-commit hooks
# into a vault's .git/hooks/pre-commit.
#
# Two steps are installed in sequence:
#   1. Status guard  (pre-commit-status-guard.sh)  — rejects non-canonical status values.
#   2. Index regen   (pre-commit-regen-indices.sh)  — regenerates _index.md files and
#      stages them so they ride along with the commit that triggered it.
#
# The two steps are separate scripts (composable, independently testable) wired
# by this installer into a single pre-commit wrapper. Keeping them as separate
# scripts (not one monolithic hook) means each can be invoked standalone for
# debugging and the installer remains the single wiring point.
#
# Usage: install-vault-hooks.sh <vault-path>
#
# Requires LORE_PLUGIN_ROOT to be set (pointing at the plugins/lore/ dir of the
# installed lore plugin). `lore init` sets this automatically.
#
# Chain-safety: if .git/hooks/pre-commit already exists and is not our wrapper,
# we emit a wrapper that runs the original hook first, then our two steps. The
# original hook is preserved byte-for-byte; we never clobber it silently.
#
# Idempotent: re-running when our wrapper is already in place is a no-op.

set -euo pipefail

VAULT="${1:-}"
if [ -z "$VAULT" ]; then
    echo "usage: install-vault-hooks.sh <vault-path>" >&2
    exit 1
fi

VAULT="$(cd "$VAULT" && pwd)"
GIT_HOOKS_DIR="$VAULT/.git/hooks"
TARGET="$GIT_HOOKS_DIR/pre-commit"

if [ ! -d "$GIT_HOOKS_DIR" ]; then
    echo "error: .git/hooks not found at $GIT_HOOKS_DIR — is $VAULT a git repo?" >&2
    exit 1
fi

if [ -z "${LORE_PLUGIN_ROOT:-}" ]; then
    echo "error: LORE_PLUGIN_ROOT is not set. Set it to the lore plugin directory." >&2
    exit 1
fi

GUARD_SH="$LORE_PLUGIN_ROOT/hooks/pre-commit-status-guard.sh"
if [ ! -f "$GUARD_SH" ]; then
    echo "error: lore guard not found at $GUARD_SH" >&2
    exit 1
fi

REGEN_SH="$LORE_PLUGIN_ROOT/hooks/pre-commit-regen-indices.sh"
if [ ! -f "$REGEN_SH" ]; then
    echo "error: lore regen hook not found at $REGEN_SH" >&2
    exit 1
fi

# Idempotent marker embedded in the wrapper we write.
# Updated from v1 to v2 to distinguish the two-step wrapper from the old single-step one.
MARKER="# lore-hooks-installed-v2"

# Already installed by us?
if [ -f "$TARGET" ] && grep -qF "$MARKER" "$TARGET" 2>/dev/null; then
    echo "lore pre-commit hooks already installed at $TARGET"
    exit 0
fi

if [ -e "$TARGET" ]; then
    # Something else is already there — chain-safe mode: save original, then
    # build a wrapper that runs original first, then our two steps.
    ORIGINAL_HOOK="$GIT_HOOKS_DIR/pre-commit-before-lore"
    cp "$TARGET" "$ORIGINAL_HOOK"
    chmod +x "$ORIGINAL_HOOK"
    echo "lore: existing pre-commit hook saved to $ORIGINAL_HOOK"

    cat > "$TARGET" <<EOF
#!/usr/bin/env bash
$MARKER
# Chain: run the original pre-commit hook, then lore's status guard and index regen.
# Original hook was saved to $ORIGINAL_HOOK at install time.

set -euo pipefail

# Run original hook first.
"$ORIGINAL_HOOK" "\$@" || exit \$?

# Run lore status guard (exits non-zero to block commits with invalid status values).
export LORE_GUARD_STRICT=1
export LORE_PLUGIN_ROOT="$LORE_PLUGIN_ROOT"
"$GUARD_SH" "\$@" || exit \$?

# Regenerate _index.md files and stage them into the current commit.
export LORE_VAULT="$VAULT"
"$REGEN_SH" "\$@"
EOF
else
    cat > "$TARGET" <<EOF
#!/usr/bin/env bash
$MARKER
# Lore vault pre-commit hooks: status guard + index regeneration.
# Generated by install-vault-hooks.sh — do not edit this header.

set -euo pipefail

# Step 1: status guard — rejects commits with non-canonical status: values.
export LORE_GUARD_STRICT=1
export LORE_PLUGIN_ROOT="$LORE_PLUGIN_ROOT"
"$GUARD_SH" "\$@" || exit \$?

# Step 2: index regen — regenerates _index.md files and stages them.
export LORE_VAULT="$VAULT"
"$REGEN_SH" "\$@"
EOF
fi

chmod +x "$TARGET"
echo "Installed lore pre-commit hooks at $TARGET"
