#!/usr/bin/env bash
# install-hooks.sh — idempotently install the forge leak-gate as a pre-commit
# hook in a target repo's .git/hooks/pre-commit.
#
# Usage: install-hooks.sh <repo-path> [<scan-subdir> ...]
#   <repo-path>    git repo whose commits should be gated.
#   <scan-subdir>  one or more dirs under the repo to scan (default: ".", the
#                  whole repo). For plugin repos, pass the shippable surface AND
#                  the test tree — both go public — e.g.
#                  "plugins/lore tests". Author-controlled root docs (README,
#                  ROADMAP) are left unscanned since they may legitimately carry
#                  the public repo-owner URL.
#
# The denylist is machine-local: $LEAK_GATE_DENYLIST or ~/.claude/leak-gate.denylist.
# If it is missing at commit time the gate fails closed (blocks the commit).
#
# Chain-safety: an existing pre-commit hook is preserved byte-for-byte and run
# first; the leak gate runs after. Re-running when our wrapper is already in
# place is a no-op (idempotent).
#
# Absolute paths are baked into the generated hook on purpose — .git/hooks/ is
# never committed or cloned, so it is inherently machine-local.

set -euo pipefail

REPO="${1:-}"
if [ -z "$REPO" ]; then
    echo "usage: install-hooks.sh <repo-path> [<scan-subdir> ...]" >&2
    exit 1
fi
shift
SCAN_SUBDIRS=("$@")
[ ${#SCAN_SUBDIRS[@]} -eq 0 ] && SCAN_SUBDIRS=(".")

REPO="$(cd "$REPO" && pwd)"
GIT_HOOKS_DIR="$REPO/.git/hooks"
TARGET="$GIT_HOOKS_DIR/pre-commit"

if [ ! -d "$GIT_HOOKS_DIR" ]; then
    echo "error: .git/hooks not found at $GIT_HOOKS_DIR — is $REPO a git repo?" >&2
    exit 1
fi

# leak_gate.py is this script's sibling.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
GATE="$SCRIPT_DIR/leak_gate.py"
if [ ! -f "$GATE" ]; then
    echo "error: leak gate not found at $GATE" >&2
    exit 1
fi

DENYLIST="${LEAK_GATE_DENYLIST:-$HOME/.claude/leak-gate.denylist}"

# Build a quoted, space-separated list of absolute scan targets for the hook.
SCAN_TARGETS_QUOTED=""
SCAN_TARGETS_DISPLAY=""
for sd in "${SCAN_SUBDIRS[@]}"; do
    SCAN_TARGETS_QUOTED+=" \"$REPO/$sd\""
    SCAN_TARGETS_DISPLAY+=" $REPO/$sd"
done

MARKER="# forge-leak-gate-installed"

# Already installed by us?
if [ -f "$TARGET" ] && grep -qF "$MARKER" "$TARGET" 2>/dev/null; then
    echo "forge leak gate already installed at $TARGET"
    exit 0
fi

if [ -e "$TARGET" ]; then
    ORIGINAL_HOOK="$GIT_HOOKS_DIR/pre-commit-before-forge"
    cp "$TARGET" "$ORIGINAL_HOOK"
    chmod +x "$ORIGINAL_HOOK"
    echo "forge: existing pre-commit hook saved to $ORIGINAL_HOOK"

    cat > "$TARGET" <<EOF
#!/usr/bin/env bash
$MARKER
# Chain: run the original pre-commit hook, then the forge leak gate.
# Original hook was saved to $ORIGINAL_HOOK at install time.

set -euo pipefail

"$ORIGINAL_HOOK" "\$@" || exit \$?

exec python3 "$GATE"$SCAN_TARGETS_QUOTED --denylist "$DENYLIST"
EOF
else
    cat > "$TARGET" <<EOF
#!/usr/bin/env bash
$MARKER
# Forge leak gate — blocks commits that would ship a private string.
# Generated by install-hooks.sh — do not edit this header.
# Denylist (machine-local): $DENYLIST

set -euo pipefail

exec python3 "$GATE"$SCAN_TARGETS_QUOTED --denylist "$DENYLIST"
EOF
fi

chmod +x "$TARGET"
echo "Installed forge leak gate at $TARGET"
echo "  scanning:$SCAN_TARGETS_DISPLAY"
echo "  denylist: $DENYLIST"
